--- 
pool: 
  vmImage: ubuntu-16.04
steps: 
  - 
    inputs: 
      command: install
    task: Npm@1
  - 
    continueOnError: true
    displayName: "Run unit tests"
    script: "npm test"
  - 
    condition: succeededOrFailed()
    displayName: "Publish Test Results"
    inputs: 
      testResultsFiles: $(System.DefaultWorkingDirectory)/test-report.xml
    task: PublishTestResults@2
  - 
    condition: "in(variables['Agent.JobStatus'], 'Succeeded')"
    displayName: "Publish Code Coverage"
    inputs: 
      codeCoverageTool: Cobertura
      reportDirectory: $(System.DefaultWorkingDirectory)/coverage
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/*coverage.xml
    task: PublishCodeCoverageResults@1
  - 
    displayName: "Archive sources"
    inputs: 
      includeRootFolder: false
      rootFolderOrFile: $(Build.SourcesDirectory)
    task: ArchiveFiles@2
  - 
    displayName: "Copy ARM templates"
    inputs: 
      Contents: "*.json"
      SourceFolder: deployment
      TargetFolder: $(build.artifactstagingdirectory)/Templates
    task: CopyFiles@2
  - 
    displayName: "Publish Artifact: drop"
    task: PublishBuildArtifacts@1
trigger: 
  - master
